//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace ThermoRawFileParser.Writer.MzML {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    [System.Xml.Serialization.XmlRootAttribute("mzML", Namespace="http://psi.hupo.org/ms/mzml", IsNullable=false)]
    public partial class mzMLType {
        
        private CVListType cvListField;
        
        private FileDescriptionType fileDescriptionField;
        
        private ReferenceableParamGroupListType referenceableParamGroupListField;
        
        private SampleListType sampleListField;
        
        private SoftwareListType softwareListField;
        
        private ScanSettingsListType scanSettingsListField;
        
        private InstrumentConfigurationListType instrumentConfigurationListField;
        
        private DataProcessingListType dataProcessingListField;
        
        private RunType runField;
        
        private string accessionField;
        
        private string versionField;
        
        private string idField;
        
        /// <remarks/>
        public CVListType cvList {
            get {
                return this.cvListField;
            }
            set {
                this.cvListField = value;
            }
        }
        
        /// <remarks/>
        public FileDescriptionType fileDescription {
            get {
                return this.fileDescriptionField;
            }
            set {
                this.fileDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public ReferenceableParamGroupListType referenceableParamGroupList {
            get {
                return this.referenceableParamGroupListField;
            }
            set {
                this.referenceableParamGroupListField = value;
            }
        }
        
        /// <remarks/>
        public SampleListType sampleList {
            get {
                return this.sampleListField;
            }
            set {
                this.sampleListField = value;
            }
        }
        
        /// <remarks/>
        public SoftwareListType softwareList {
            get {
                return this.softwareListField;
            }
            set {
                this.softwareListField = value;
            }
        }
        
        /// <remarks/>
        public ScanSettingsListType scanSettingsList {
            get {
                return this.scanSettingsListField;
            }
            set {
                this.scanSettingsListField = value;
            }
        }
        
        /// <remarks/>
        public InstrumentConfigurationListType instrumentConfigurationList {
            get {
                return this.instrumentConfigurationListField;
            }
            set {
                this.instrumentConfigurationListField = value;
            }
        }
        
        /// <remarks/>
        public DataProcessingListType dataProcessingList {
            get {
                return this.dataProcessingListField;
            }
            set {
                this.dataProcessingListField = value;
            }
        }
        
        /// <remarks/>
        public RunType run {
            get {
                return this.runField;
            }
            set {
                this.runField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string accession {
            get {
                return this.accessionField;
            }
            set {
                this.accessionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class CVListType {
        
        private CVType[] cvTypeField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cv")]
        public CVType[] CvType {
            get {
                return this.cvTypeField;
            }
            set {
                this.cvTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    [System.Xml.Serialization.XmlRootAttribute("cv", Namespace="http://psi.hupo.org/ms/mzml", IsNullable=false)]
    public partial class CVType {
        
        private string idField;
        
        private string fullNameField;
        
        private string versionField;
        
        private string uRIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class OffsetType {
        
        private string idRefField;
        
        private string spotIDField;
        
        private double scanTimeField;
        
        private bool scanTimeFieldSpecified;
        
        private long valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string idRef {
            get {
                return this.idRefField;
            }
            set {
                this.idRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string spotID {
            get {
                return this.spotIDField;
            }
            set {
                this.spotIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double scanTime {
            get {
                return this.scanTimeField;
            }
            set {
                this.scanTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scanTimeSpecified {
            get {
                return this.scanTimeFieldSpecified;
            }
            set {
                this.scanTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public long Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class IndexType {
        
        private OffsetType[] offsetField;
        
        private IndexTypeName nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("offset")]
        public OffsetType[] offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public IndexTypeName name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://psi.hupo.org/ms/mzml")]
    public enum IndexTypeName {
        
        /// <remarks/>
        spectrum,
        
        /// <remarks/>
        chromatogram,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class IndexListType {
        
        private IndexType[] indexField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("index")]
        public IndexType[] index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class DataProcessingType {
        
        private ProcessingMethodType[] processingMethodField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("processingMethod")]
        public ProcessingMethodType[] processingMethod {
            get {
                return this.processingMethodField;
            }
            set {
                this.processingMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class ProcessingMethodType : ParamGroupType {
        
        private string orderField;
        
        private string softwareRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string softwareRef {
            get {
                return this.softwareRefField;
            }
            set {
                this.softwareRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChromatogramType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BinaryDataArrayType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ScanType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ScanListType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SpectrumType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RunType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ScanSettingsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProcessingMethodType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoftwareType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstrumentConfigurationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComponentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AnalyzerComponentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DetectorComponentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SourceComponentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SampleType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SourceFileType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class ParamGroupType {
        
        private ReferenceableParamGroupRefType[] referenceableParamGroupRefField;
        
        private CVParamType[] cvParamField;
        
        private UserParamType[] userParamField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referenceableParamGroupRef")]
        public ReferenceableParamGroupRefType[] referenceableParamGroupRef {
            get {
                return this.referenceableParamGroupRefField;
            }
            set {
                this.referenceableParamGroupRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cvParam")]
        public CVParamType[] cvParam {
            get {
                return this.cvParamField;
            }
            set {
                this.cvParamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userParam")]
        public UserParamType[] userParam {
            get {
                return this.userParamField;
            }
            set {
                this.userParamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class ReferenceableParamGroupRefType {
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    [System.Xml.Serialization.XmlRootAttribute("cvParam", Namespace="http://psi.hupo.org/ms/mzml", IsNullable=false)]
    public partial class CVParamType {
        
        private string cvRefField;
        
        private string accessionField;
        
        private string valueField;
        
        private string nameField;
        
        private string unitAccessionField;
        
        private string unitNameField;
        
        private string unitCvRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string cvRef {
            get {
                return this.cvRefField;
            }
            set {
                this.cvRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string accession {
            get {
                return this.accessionField;
            }
            set {
                this.accessionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string unitAccession {
            get {
                return this.unitAccessionField;
            }
            set {
                this.unitAccessionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string unitName {
            get {
                return this.unitNameField;
            }
            set {
                this.unitNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string unitCvRef {
            get {
                return this.unitCvRefField;
            }
            set {
                this.unitCvRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class UserParamType {
        
        private string nameField;
        
        private string typeField;
        
        private string valueField;
        
        private string unitAccessionField;
        
        private string unitNameField;
        
        private string unitCvRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string unitAccession {
            get {
                return this.unitAccessionField;
            }
            set {
                this.unitAccessionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string unitName {
            get {
                return this.unitNameField;
            }
            set {
                this.unitNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string unitCvRef {
            get {
                return this.unitCvRefField;
            }
            set {
                this.unitCvRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    [System.Xml.Serialization.XmlRootAttribute("chromatogram", Namespace="http://psi.hupo.org/ms/mzml", IsNullable=false)]
    public partial class ChromatogramType : ParamGroupType {
        
        private PrecursorType precursorField;
        
        private ProductType productField;
        
        private BinaryDataArrayListType binaryDataArrayListField;
        
        private string idField;
        
        private string indexField;
        
        private int defaultArrayLengthField;
        
        private string dataProcessingRefField;
        
        /// <remarks/>
        public PrecursorType precursor {
            get {
                return this.precursorField;
            }
            set {
                this.precursorField = value;
            }
        }
        
        /// <remarks/>
        public ProductType product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        public BinaryDataArrayListType binaryDataArrayList {
            get {
                return this.binaryDataArrayListField;
            }
            set {
                this.binaryDataArrayListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int defaultArrayLength {
            get {
                return this.defaultArrayLengthField;
            }
            set {
                this.defaultArrayLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string dataProcessingRef {
            get {
                return this.dataProcessingRefField;
            }
            set {
                this.dataProcessingRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class PrecursorType {
        
        private ParamGroupType isolationWindowField;
        
        private SelectedIonListType selectedIonListField;
        
        private ParamGroupType activationField;
        
        private string spectrumRefField;
        
        private string sourceFileRefField;
        
        private string externalSpectrumIDField;
        
        /// <remarks/>
        public ParamGroupType isolationWindow {
            get {
                return this.isolationWindowField;
            }
            set {
                this.isolationWindowField = value;
            }
        }
        
        /// <remarks/>
        public SelectedIonListType selectedIonList {
            get {
                return this.selectedIonListField;
            }
            set {
                this.selectedIonListField = value;
            }
        }
        
        /// <remarks/>
        public ParamGroupType activation {
            get {
                return this.activationField;
            }
            set {
                this.activationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string spectrumRef {
            get {
                return this.spectrumRefField;
            }
            set {
                this.spectrumRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string sourceFileRef {
            get {
                return this.sourceFileRefField;
            }
            set {
                this.sourceFileRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string externalSpectrumID {
            get {
                return this.externalSpectrumIDField;
            }
            set {
                this.externalSpectrumIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class SelectedIonListType {
        
        private ParamGroupType[] selectedIonField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("selectedIon")]
        public ParamGroupType[] selectedIon {
            get {
                return this.selectedIonField;
            }
            set {
                this.selectedIonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class ProductType {
        
        private ParamGroupType isolationWindowField;
        
        /// <remarks/>
        public ParamGroupType isolationWindow {
            get {
                return this.isolationWindowField;
            }
            set {
                this.isolationWindowField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class BinaryDataArrayListType {
        
        private BinaryDataArrayType[] binaryDataArrayField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("binaryDataArray")]
        public BinaryDataArrayType[] binaryDataArray {
            get {
                return this.binaryDataArrayField;
            }
            set {
                this.binaryDataArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class BinaryDataArrayType : ParamGroupType {
        
        private byte[] binaryField;
        
        private string arrayLengthField;
        
        private string dataProcessingRefField;
        
        private string encodedLengthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] binary {
            get {
                return this.binaryField;
            }
            set {
                this.binaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string arrayLength {
            get {
                return this.arrayLengthField;
            }
            set {
                this.arrayLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string dataProcessingRef {
            get {
                return this.dataProcessingRefField;
            }
            set {
                this.dataProcessingRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string encodedLength {
            get {
                return this.encodedLengthField;
            }
            set {
                this.encodedLengthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class ScanType : ParamGroupType {
        
        private ScanWindowListType scanWindowListField;
        
        private string spectrumRefField;
        
        private string sourceFileRefField;
        
        private string externalSpectrumIDField;
        
        private string instrumentConfigurationRefField;
        
        /// <remarks/>
        public ScanWindowListType scanWindowList {
            get {
                return this.scanWindowListField;
            }
            set {
                this.scanWindowListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string spectrumRef {
            get {
                return this.spectrumRefField;
            }
            set {
                this.spectrumRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string sourceFileRef {
            get {
                return this.sourceFileRefField;
            }
            set {
                this.sourceFileRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string externalSpectrumID {
            get {
                return this.externalSpectrumIDField;
            }
            set {
                this.externalSpectrumIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string instrumentConfigurationRef {
            get {
                return this.instrumentConfigurationRefField;
            }
            set {
                this.instrumentConfigurationRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class ScanWindowListType {
        
        private ParamGroupType[] scanWindowField;
        
        private int countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("scanWindow")]
        public ParamGroupType[] scanWindow {
            get {
                return this.scanWindowField;
            }
            set {
                this.scanWindowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class ScanListType : ParamGroupType {
        
        private ScanType[] scanField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("scan")]
        public ScanType[] scan {
            get {
                return this.scanField;
            }
            set {
                this.scanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    [System.Xml.Serialization.XmlRootAttribute("spectrum", Namespace="http://psi.hupo.org/ms/mzml", IsNullable=false)]
    public partial class SpectrumType : ParamGroupType {
        
        private ScanListType scanListField;
        
        private PrecursorListType precursorListField;
        
        private ProductListType productListField;
        
        private BinaryDataArrayListType binaryDataArrayListField;
        
        private string idField;
        
        private string spotIDField;
        
        private string indexField;
        
        private int defaultArrayLengthField;
        
        private string dataProcessingRefField;
        
        private string sourceFileRefField;
        
        /// <remarks/>
        public ScanListType scanList {
            get {
                return this.scanListField;
            }
            set {
                this.scanListField = value;
            }
        }
        
        /// <remarks/>
        public PrecursorListType precursorList {
            get {
                return this.precursorListField;
            }
            set {
                this.precursorListField = value;
            }
        }
        
        /// <remarks/>
        public ProductListType productList {
            get {
                return this.productListField;
            }
            set {
                this.productListField = value;
            }
        }
        
        /// <remarks/>
        public BinaryDataArrayListType binaryDataArrayList {
            get {
                return this.binaryDataArrayListField;
            }
            set {
                this.binaryDataArrayListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string spotID {
            get {
                return this.spotIDField;
            }
            set {
                this.spotIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int defaultArrayLength {
            get {
                return this.defaultArrayLengthField;
            }
            set {
                this.defaultArrayLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string dataProcessingRef {
            get {
                return this.dataProcessingRefField;
            }
            set {
                this.dataProcessingRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string sourceFileRef {
            get {
                return this.sourceFileRefField;
            }
            set {
                this.sourceFileRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class PrecursorListType {
        
        private PrecursorType[] precursorField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("precursor")]
        public PrecursorType[] precursor {
            get {
                return this.precursorField;
            }
            set {
                this.precursorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class ProductListType {
        
        private ProductType[] productField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("product")]
        public ProductType[] product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class RunType : ParamGroupType {
        
        private SpectrumListType spectrumListField;
        
        private ChromatogramListType chromatogramListField;
        
        private string idField;
        
        private string defaultInstrumentConfigurationRefField;
        
        private string defaultSourceFileRefField;
        
        private string sampleRefField;
        
        private System.DateTime startTimeStampField;
        
        private bool startTimeStampFieldSpecified;
        
        /// <remarks/>
        public SpectrumListType spectrumList {
            get {
                return this.spectrumListField;
            }
            set {
                this.spectrumListField = value;
            }
        }
        
        /// <remarks/>
        public ChromatogramListType chromatogramList {
            get {
                return this.chromatogramListField;
            }
            set {
                this.chromatogramListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string defaultInstrumentConfigurationRef {
            get {
                return this.defaultInstrumentConfigurationRefField;
            }
            set {
                this.defaultInstrumentConfigurationRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string defaultSourceFileRef {
            get {
                return this.defaultSourceFileRefField;
            }
            set {
                this.defaultSourceFileRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string sampleRef {
            get {
                return this.sampleRefField;
            }
            set {
                this.sampleRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime startTimeStamp {
            get {
                return this.startTimeStampField;
            }
            set {
                this.startTimeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startTimeStampSpecified {
            get {
                return this.startTimeStampFieldSpecified;
            }
            set {
                this.startTimeStampFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class SpectrumListType {
        
        private SpectrumType[] spectrumField;
        
        private string countField;
        
        private string defaultDataProcessingRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("spectrum")]
        public SpectrumType[] spectrum {
            get {
                return this.spectrumField;
            }
            set {
                this.spectrumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string defaultDataProcessingRef {
            get {
                return this.defaultDataProcessingRefField;
            }
            set {
                this.defaultDataProcessingRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]    
    public partial class ChromatogramListType {
        
        private ChromatogramType[] chromatogramField;
        
        private string countField;
        
        private string defaultDataProcessingRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("chromatogram")]
        public ChromatogramType[] chromatogram {
            get {
                return this.chromatogramField;
            }
            set {
                this.chromatogramField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string defaultDataProcessingRef {
            get {
                return this.defaultDataProcessingRefField;
            }
            set {
                this.defaultDataProcessingRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class ScanSettingsType : ParamGroupType {
        
        private SourceFileRefListType sourceFileRefListField;
        
        private TargetListType targetListField;
        
        private string idField;
        
        /// <remarks/>
        public SourceFileRefListType sourceFileRefList {
            get {
                return this.sourceFileRefListField;
            }
            set {
                this.sourceFileRefListField = value;
            }
        }
        
        /// <remarks/>
        public TargetListType targetList {
            get {
                return this.targetListField;
            }
            set {
                this.targetListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class SourceFileRefListType {
        
        private SourceFileRefType[] sourceFileRefField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sourceFileRef")]
        public SourceFileRefType[] sourceFileRef {
            get {
                return this.sourceFileRefField;
            }
            set {
                this.sourceFileRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class SourceFileRefType {
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class TargetListType {
        
        private ParamGroupType[] targetField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("target")]
        public ParamGroupType[] target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class SoftwareType : ParamGroupType {
        
        private string idField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class InstrumentConfigurationType : ParamGroupType {
        
        private ComponentListType componentListField;
        
        private SoftwareRefType softwareRefField;
        
        private string idField;
        
        private string scanSettingsRefField;
        
        /// <remarks/>
        public ComponentListType componentList {
            get {
                return this.componentListField;
            }
            set {
                this.componentListField = value;
            }
        }
        
        /// <remarks/>
        public SoftwareRefType softwareRef {
            get {
                return this.softwareRefField;
            }
            set {
                this.softwareRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string scanSettingsRef {
            get {
                return this.scanSettingsRefField;
            }
            set {
                this.scanSettingsRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class ComponentListType {
        
        private SourceComponentType[] sourceField;
        
        private AnalyzerComponentType[] analyzerField;
        
        private DetectorComponentType[] detectorField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("source")]
        public SourceComponentType[] source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("analyzer")]
        public AnalyzerComponentType[] analyzer {
            get {
                return this.analyzerField;
            }
            set {
                this.analyzerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detector")]
        public DetectorComponentType[] detector {
            get {
                return this.detectorField;
            }
            set {
                this.detectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class SourceComponentType : ComponentType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AnalyzerComponentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DetectorComponentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SourceComponentType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class ComponentType : ParamGroupType {
        
        private int orderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class AnalyzerComponentType : ComponentType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class DetectorComponentType : ComponentType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class SoftwareRefType {
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class SampleType : ParamGroupType {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class SourceFileType : ParamGroupType {
        
        private string idField;
        
        private string nameField;
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class DataProcessingListType {
        
        private DataProcessingType[] dataProcessingField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dataProcessing")]
        public DataProcessingType[] dataProcessing {
            get {
                return this.dataProcessingField;
            }
            set {
                this.dataProcessingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class InstrumentConfigurationListType {
        
        private InstrumentConfigurationType[] instrumentConfigurationField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("instrumentConfiguration")]
        public InstrumentConfigurationType[] instrumentConfiguration {
            get {
                return this.instrumentConfigurationField;
            }
            set {
                this.instrumentConfigurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class ScanSettingsListType {
        
        private ScanSettingsType[] scanSettingsField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("scanSettings")]
        public ScanSettingsType[] scanSettings {
            get {
                return this.scanSettingsField;
            }
            set {
                this.scanSettingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class SoftwareListType {
        
        private SoftwareType[] softwareField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("software")]
        public SoftwareType[] software {
            get {
                return this.softwareField;
            }
            set {
                this.softwareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class SampleListType {
        
        private SampleType[] sampleField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sample")]
        public SampleType[] sample {
            get {
                return this.sampleField;
            }
            set {
                this.sampleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class ReferenceableParamGroupType {
        
        private CVParamType[] cvParamField;
        
        private UserParamType[] userParamField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cvParam")]
        public CVParamType[] cvParam {
            get {
                return this.cvParamField;
            }
            set {
                this.cvParamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userParam")]
        public UserParamType[] userParam {
            get {
                return this.userParamField;
            }
            set {
                this.userParamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class ReferenceableParamGroupListType {
        
        private ReferenceableParamGroupType[] referenceableParamGroupField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referenceableParamGroup")]
        public ReferenceableParamGroupType[] referenceableParamGroup {
            get {
                return this.referenceableParamGroupField;
            }
            set {
                this.referenceableParamGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class SourceFileListType {
        
        private SourceFileType[] sourceFileField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sourceFile")]
        public SourceFileType[] sourceFile {
            get {
                return this.sourceFileField;
            }
            set {
                this.sourceFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://psi.hupo.org/ms/mzml")]
    public partial class FileDescriptionType {
        
        private ParamGroupType fileContentField;
        
        private SourceFileListType sourceFileListField;
        
        private ParamGroupType[] contactField;
        
        /// <remarks/>
        public ParamGroupType fileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
            }
        }
        
        /// <remarks/>
        public SourceFileListType sourceFileList {
            get {
                return this.sourceFileListField;
            }
            set {
                this.sourceFileListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contact")]
        public ParamGroupType[] contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://psi.hupo.org/ms/mzml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://psi.hupo.org/ms/mzml", IsNullable=false)]
    public partial class indexedmzML {
        
        private mzMLType mzMLField;
        
        private IndexListType indexListField;
        
        private System.Nullable<long> indexListOffsetField;
        
        private string fileChecksumField;
        
        /// <remarks/>
        public mzMLType mzML {
            get {
                return this.mzMLField;
            }
            set {
                this.mzMLField = value;
            }
        }
        
        /// <remarks/>
        public IndexListType indexList {
            get {
                return this.indexListField;
            }
            set {
                this.indexListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> indexListOffset {
            get {
                return this.indexListOffsetField;
            }
            set {
                this.indexListOffsetField = value;
            }
        }
        
        /// <remarks/>
        public string fileChecksum {
            get {
                return this.fileChecksumField;
            }
            set {
                this.fileChecksumField = value;
            }
        }
    }
}
